Removes the created text area [web] (#1145)
* Removes the created text area

ReferenceError: textArea is not defined

* Working approach

Removing the textarea before alert function to avoid rendering the element.
Not using promises since no es6 is used.